### First we import numpy

In [1]:
import numpy as np

### Now we make a matrix

In [6]:
m = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

m = np.matrix(m)

print(m)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Make another matrix to hold the transposed values

In [7]:
k = np.matrix((np.zeros((m.shape[1], m.shape[0]))), dtype=int)
print(k)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### We do the transpose

In [8]:
for i in range(m.shape[0]):
    for j in range(m.shape[1]):
        k[j,i] = m[i,j]
print(k)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


### Check the results with numpy

In [9]:
print(m.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
